#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    public partial class _test_cshtml : RazorGenerator.Templating.RazorTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral(@"<?xml version=""1.0"" encoding=""UTF-8"" ?>
<!DOCTYPE report [
          ]>
<report>
    <title>Title of report</title>
    <content>
        <pageSequence orientation=""portrait"">
            <htmlBlock>
                <h1>Report</h1>
            </htmlBlock>
        </pageSequence>
    </content>
</report>");


        }
    }
}
#pragma warning restore 1591
